export default {
  default: {
    //validate
    'validate.can_not_be_empty': 'This field cannot be empty',
    'validate.field_can_not_be_empty': '{{field}} cannot be empty',
    'validate.please_input_field': 'Please enter {{field}}',
    'validate.must_be_larger_than_0': 'Value must be greater than 0',
    'validate.must_be_a_number': 'Value must be a number',
    'validate.field_must_be_larger_than_0': '{{field}} must be greater than 0',
    'validate.field_must_be_a_number': '{{field}} must be a number',
    'validate.need_at_least_26_characters': 'Must be at least 26 characters',
    'validate.need_at_least_66_characters': 'Requires at least 66 characters',

    //common
    'common.read_more': 'Read more',
    'common.hide': 'Hide',
    'common.and': 'and',
    'common.cancel': 'Cancel',
    'common.action': 'Action',
    'common.delete': 'Are you sure delete {{value}}?',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    validate_invalid_address: 'Invalid address',
    validate_invalid_pubkey: 'Invalid pubkey',

    All: 'All',
    Succeed: 'Success',
    Submitted: 'Sent',
    Cancel: 'Cancel',
    Pending: 'Waiting',
    Processing: 'Processing',
    Executed: 'Match',
    Executing: 'Executing',
    Market: 'Market',
    Limit: 'Limit',
    Sell: 'Sell',
    Buy: 'Buy',
    Stopping: 'Stopping',
    Error: 'Error',
    Canceled: 'Canceled',

    //file
    'file-size-required': 'The file must be less than {{value}}!',
    'unsupport-file': 'This file type is not supported',

    //header
    header: {
      username: 'Username',
      last_login: 'Last login',
      logout: 'Logout',
    },

    //Sign
    'sign.error': 'Sign error',

    //Notification
    'Notification.info': 'Notification',
    'Notification.warning': 'Warning',
    'Notification.error': 'Error',
    'Notification.success': 'Success',

    //BaseRequest
    'BaseRequest.info': 'Information',
    'BaseRequest.error': 'Error',
    'BaseRequest.result_undefined': 'The result is undefined',
    'BaseRequest.data_not_existed': 'Data is not existed',
    'BaseRequest.user_info_empty': 'User information is empty',
    'BaseRequest.contract_address_required': 'Contract address can not be empty',
    'BaseRequest.image_require': 'Symbol can not be empty',
    'BaseRequest.contract_address_invalid': 'Invalid contract address',
    'BaseRequest.require_limit_value_greater_than': 'Limit must be greater than or equal 0.00000001',
    'BaseRequest.length_must_be_between_26_and_42': 'Must have between 26 and 42 characters',
    'BaseRequest.fee': 'Fee',
    'BaseRequest.cannot_empty': 'Can not be empty',
    'BaseRequest.existed': 'Existed',
    'BaseRequest.system_having_problems': 'The system have some problems',
    'BaseRequest.withdraw_exceed_limit': 'Transfer amount is over limit',

    //Wallet
    'WalletPage.coin': 'Coin',
    'WalletPage.name_coin': 'Name',
    'WalletPage.balance': 'Balance',
    'WalletPage.available_balance': 'Available balance',
    'WalletPage.action': 'Action',
    'WalletPage.account': 'Account',
    'WalletPage.estimated_price': 'Estimated price',
    'WalletPage.personal_wallet': 'Personal wallet',
    'WalletPage.hide_coins_with_zero_balance': 'Hide coins with zero balance',
    'WalletPage.enter_the_name': 'Enter the name',
    'WalletPage.select_network': 'Select network',
    'WalletPage.internal_transfers_are_free_on_trustKeys': 'Internal transfers are free on TrustKeys.',
    'WalletPage.from': 'From',
    'WalletPage.to': 'To',
    'WalletPage.amount': 'Amount',
    'WalletPage.available': '{{available_balance}} {{coinSymbol}} available',
    'WalletPage.max': 'Max',
    'WalletPage.your_wallet_balance_is_not_enough': 'Your wallet balance is insufficient',
    'WalletPage.transfer': 'Transfer',
    'WalletPage.transfer_succeeded': 'Transfer successful',

    //Transaction History
    'Transaction.id': 'ID',
    'Transaction.currency': 'Currency',
    'Transaction.fee': 'Fee',
    'Transaction.amount': 'Amount',
    'Transaction.status': 'Status',
    'Transaction.deposit_history': 'Deposit and withdrawal history',
    'Transaction.transaction_type': 'Transaction type',
    'Transaction.deposits': 'Load',
    'Transaction.withdrawal': 'Withdraw',
    'Transaction.coin': 'Dong',
    'Transaction.rejected': 'Rejected',
    'Transaction.date': 'Time',
    'Transaction.start_date': 'Start',
    'Transaction.end_date': 'End',
    'Transaction.type': 'Transaction type',
    'Transaction.intro': 'Invite your friends to TrustKeys and earn transaction fees from them',
    'Transaction.link': 'Your referrer:',
    'Transaction.content': 'Content',
    'Transaction.detail': 'Details',

    'Deposit.charge_money': 'Cryptocurrency deposit',
    'Deposit.money': 'Money',
    'Deposit.total_balance': 'Total balance:',
    'Deposit.avai_balance': 'Available balances:',
    'Deposit.charge_money_noti': 'Recharge Notice',

    'Deposit.start_trans': 'Start trading:',
    'Deposit.net_name': 'Network Name',

    'Deposit.deposit_from_wallet': 'Deposit from wallet',
    'Deposit.wallet.connect_with': 'Deposit',
    'Deposit.wallet.reset': 'Reset',
    'Deposit.wallet.gasfee': 'Gas Fee',
    'Deposit.wallet.max': 'Max',
    'Deposit.wallet.amount': 'Amount',
    'Deposit.wallet.wrongAddress': 'Your wallet is on the wrong network',
    'Deposit.wallet.success_notify': 'Deposit successful',
    'Deposit.avarage_time': 'Average arrival time',
    'Deposit.minute': 'minute(s)',
    'Deposit.address': 'Address',
    'Deposit.charge_history': 'Most recent recharge history',
    'Deposit.send_modal': 'Send coin',
    'Deposit.name': 'Name',
    'Deposit.charge_fee': 'Recharge fee',
    'Deposit.amount': 'Amount',
    'Deposit.charge_date': 'Loading date',
    'Deposit.status': 'Status',
    'Deposit.copy_success': 'Copy address successfully',
    'Deposit.select_coin': 'Select coin',

    'Deposit.expected_arrival': 'Expected arrival',
    'Deposit.expected_unlock': 'Expected unlock',
    'Deposit.1_network_confirmations': '1 network confirmations',
    'Deposit.network_confirmations': '{{confirmation}} network confirmations',

    'Withdraw.withdraw_money': 'Withdraw cryptocurrency',
    'Withdraw.network': 'Network',
    'Withdraw.recent_address': 'Recent_address',

    'Withdraw.coin': 'Coin',
    'Withdraw.total_balance': 'Total balance',
    'Withdraw.minimum_withdrawal': 'Minimum withdrawal amount',
    'Withdraw.amount': 'Withdraw amount',
    'Withdraw.the_wallet_address_automatically_matches_the_corresponding_network':
      'The wallet address automatically matches the corresponding network.',
    'Withdraw.select_withdrawal_network': 'Select withdrawal network',
    'Withdraw.withdrawn': 'Withdrawn {{available_balance}} {{coinSymbol}}',
    'Withdraw.amount_received': 'Amount received',
    'Withdraw.total': 'Total',
    'Withdraw.fees': 'Fees',
    'Withdraw.you_need_to_pay': 'You need to pay: ',
    'Withdraw.network_fee': 'Network fee',
    'Withdraw.withdrawal': 'Withdraw',
    'Withdraw.content': 'Content\n(Optional)',
    'Withdraw.minimum_transaction_amount_is': 'Minimum transaction amount is {{min}}',
    'Withdraw.balance_insufficient': 'Your balance is not enough',
    'Withdraw.withdraw_succeeded': 'Withdraw successful',
    'Withdraw.confirm_withdraw': 'Are you sure you want to make the transaction?',

    'Withdraw.24h_limit': 'Withdrawal limit 24h',
    'Withdraw.24h_limit_transfer': 'Withdrawal 24h limit',
    'Withdraw.unlimited': 'Infinite',
    'Withdraw.hide_assets': 'Hide low balance coins',
    'Withdraw.24h_remaining_limit': '24h remaining limit',

    'Withdraw.modal_chooose_network.title': 'Select network',
    'Withdraw.modal_chooose_network.warning': 'Make sure the network matches the entered network address to avoid loss of withdrawal.',
    'Withdraw.modal_chooose_network.text': 'Non-matching networks will be removed automatically. Select a network below',
    'Withdraw.modal_chooose_network.noti_block': 'Blocked',

    'Withdraw.modal_recent_address.title': 'List of nearest withdrawal addresses',
  },
};
