export default {
  default: {
    //validate
    'validate.can_not_be_empty': 'Trường này không được bỏ trống!',
    'validate.field_can_not_be_empty': '{{field}} không được bỏ trống!',
    'validate.please_input_field': 'Hãy nhập {{field}}',
    'validate.must_be_larger_than_0': 'Giá trị phải lớn hơn 0',
    'validate.must_be_a_number': 'Giá trị phải là một số',
    'validate.field_must_be_larger_than_0': '{{field}} phải lớn hơn không',
    'validate.field_must_be_a_number': '{{field}} phải là một số',
    'validate.need_at_least_26_characters': 'Cần phải có ít nhất 26 ký tự',
    'validate.need_at_least_66_characters': 'Cần phải có ít nhất 66 ký tự',

    //common
    'common.read_more': 'Xem thêm',
    'common.hide': 'Ẩn bớt',
    'common.and': 'và',
    'common.cancel': 'Hủy',
    'common.action': 'Hành động',
    'common.delete': 'Bạn có chắc chắn xóa {{value}}?',
    'common.success': 'Thành công',
    'common.confirm': 'Xác nhận',
    validate_invalid_address: 'Địa chỉ không hợp lệ',
    validate_invalid_pubkey: 'Pubkey không hợp lệ',

    All: 'Tất cả',
    Succeed: 'Thành công',
    Submitted: 'Đã gửi',
    Cancel: 'Hủy',
    Pending: 'Đang chờ',
    Processing: 'Đang xử lý',
    Executed: 'Đã khớp',
    Executing: 'Đang thực thi',
    Market: 'Thị trường',
    Limit: 'Giới hạn',
    Sell: 'Bán',
    Buy: 'Mua',
    Stopping: 'Đang dừng',
    Error: 'Lỗi',
    Canceled: 'Đã hủy',

    //file
    'file-size-required': 'Tệp phải có dung lượng nhỏ hơn {{value}}!',
    'unsupport-file': 'Không hỗ trợ loại tệp này',

    //header
    header: {
      username: 'Tên người dùng',
      last_login: 'Lần đăng nhập cuối',
      logout: 'Đăng xuất',
    },

    //Sign
    'sign.error': 'Ký xảy ra lỗi',

    //Notification
    'Notification.info': 'Thông báo',
    'Notification.warning': 'Cảnh báo',
    'Notification.error': 'Lỗi',
    'Notification.success': 'Thành công',

    //BaseRequest
    'BaseRequest.info': 'Thông tin',
    'BaseRequest.error': 'Lỗi',
    'BaseRequest.result_undefined': 'Kết quả không xác định',
    'BaseRequest.data_not_existed': 'Dữ liệu không tồn tại',
    'BaseRequest.user_info_empty': 'Thông tin người dùng rỗng',
    'BaseRequest.contract_address_required': 'Mã giao dịch không được để trống',
    'BaseRequest.image_require': 'Biểu tượng không đươc để trống',
    'BaseRequest.contract_address_invalid': 'Mã giao dịch không tồn tại',
    'BaseRequest.require_limit_value_greater_than': 'Giới hạn phải lớn hơn hoặc bằng 0.00000001',
    'BaseRequest.length_must_be_between_26_and_42': 'Địa chỉ phải có từ 26 đến 42 kí tự',
    'BaseRequest.fee': 'Phí',
    'BaseRequest.cannot_empty': 'Không được bỏ trống',
    'BaseRequest.existed': 'Đã tồn tại',
    'BaseRequest.system_having_problems': 'Hệ thống đang có sự cố',
    'BaseRequest.withdraw_exceed_limit': 'Số tiền chuyển quá giới hạn',

    //Wallet
    'WalletPage.coin': 'Đồng',
    'WalletPage.name_coin': 'Tên',
    'WalletPage.balance': 'Số dư',
    'WalletPage.available_balance': 'Số dư có sẵn',
    'WalletPage.action': 'Hành động',
    'WalletPage.account': 'Tài khoản',
    'WalletPage.estimated_price': 'Giá ước lượng',
    'WalletPage.personal_wallet': 'Ví cá nhân',
    'WalletPage.hide_coins_with_zero_balance': 'Ẩn các đồng có số dư bằng 0',
    'WalletPage.enter_the_name': 'Nhập tên đồng',
    'WalletPage.select_network': 'Chọn mạng',
    'WalletPage.internal_transfers_are_free_on_trustKeys': 'Miễn phí chuyển nội bộ trong TrustKeys.',
    'WalletPage.from': 'Từ',
    'WalletPage.to': 'Đến',
    'WalletPage.amount': 'Số tiền',
    'WalletPage.available': '{{available_balance}} {{coinSymbol}} khả dụng',
    'WalletPage.max': 'Tối đa',
    'WalletPage.your_wallet_balance_is_not_enough': 'Số dư trong ví của bạn không đủ',
    'WalletPage.transfer': 'Chuyển đổi',
    'WalletPage.transfer_succeeded': 'Chuyển tiền thành công',

    //Transaction History
    'Transaction.id': 'ID',
    'Transaction.currency': 'Tiền tệ',
    'Transaction.fee': 'Phí',
    'Transaction.amount': 'Số lượng',
    'Transaction.status': 'Trạng thái',
    'Transaction.deposit_history': 'Lịch sử nạp và rút',
    'Transaction.transaction_type': 'Loại giao dịch',
    'Transaction.deposits': 'Nạp',
    'Transaction.withdrawal': 'Rút',
    'Transaction.coin': 'Đồng',
    'Transaction.rejected': 'Từ chối',
    'Transaction.date': 'Thời gian',
    'Transaction.start_date': 'Bắt đầu',
    'Transaction.end_date': 'Kết thúc',
    'Transaction.type': 'Loại giao dịch',
    'Transaction.intro': 'Mời bạn bè của bạn đến TrustKeys và kiếm phí giao dịch từ họ',
    'Transaction.link': 'Liên kết giới thiệu của bạn:',
    'Transaction.content': 'Nội dung',
    'Transaction.detail': 'Chi tiết',

    //Deposit

    'Deposit.charge_money': 'Nạp tiền mã hoá',
    'Deposit.money': 'Tiền',
    'Deposit.total_balance': 'Tổng số dư:',
    'Deposit.avai_balance': 'Số dư có sẵn:',
    'Deposit.charge_money_noti': 'Thông báo nạp tiền',
    'Deposit.start_trans': 'Bắt đầu giao dịch:',
    'Deposit.net_name': 'Tên mạng',
    'Deposit.deposit_from_wallet': 'Nạp tiền từ ví',
    'Deposit.wallet.connect_with': 'Nạp',
    'Deposit.wallet.reset': 'Nhập lại',
    'Deposit.wallet.gasfee': 'Phí gas',
    'Deposit.wallet.max': 'Tối đa',
    'Deposit.wallet.amount': 'Số lượng',
    'Deposit.wallet.wrongAddress': 'Ví của bạn đang ở sai mạng',
    'Deposit.wallet.success_notify': 'Nạp thành công',
    'Deposit.avarage_time': 'Thời gian đến trung bình',
    'Deposit.minute': 'phút',
    'Deposit.address': 'Địa chỉ',
    'Deposit.charge_history': 'Lịch sử nạp gần nhất',
    'Deposit.send_modal': 'Nạp coin',
    'Deposit.name': 'Tên',
    'Deposit.charge_fee': 'Phí nạp',
    'Deposit.amount': 'Số lượng',
    'Deposit.charge_date': 'Ngày nạp',
    'Deposit.status': 'Trạng thái',
    'Deposit.copy_success': 'Sao chép địa chỉ thành công',
    'Deposit.select_coin': 'Chọn loại coin',

    'Deposit.expected_arrival': 'Số lượng dự kiến đến',
    'Deposit.expected_unlock': 'Số lượng mở khóa dự kiến',
    'Deposit.1_network_confirmations': 'Mạng lưới xác nhận 1 lần',
    'Deposit.network_confirmations': 'Mạng lưới xác nhận {{confirmation}} lần',

    'Withdraw.withdraw_money': 'Rút tiền mã hóa',
    'Withdraw.network': 'Mạng lưới',
    'Withdraw.recent_address': 'Địa chỉ gần đây',
    'Withdraw.coin': 'Đồng',
    'Withdraw.total_balance': 'Tổng số dư',
    'Withdraw.minimum_withdrawal': 'Số tiền rút nhỏ nhất',
    'Withdraw.amount': 'Số tiền rút',
    'Withdraw.text-4.2': 'Hạn mức còn lại trong 24h',
    'Withdraw.withdrawal': 'Rút',
    'Withdraw.the_wallet_address_automatically_matches_the_corresponding_network': 'Địa chỉ ví tự động khớp với mạng tương ứng.',
    'Withdraw.select_withdrawal_network': 'Chọn mạng rút tiền',
    'Withdraw.withdrawn': 'Được rút {{available_balance}} {{coinSymbol}}',
    'Withdraw.amount_received': 'Số tiền nhận',
    'Rút tiền.total': 'Tổng',
    'Withdraw.fees': 'Phí',
    'Withdraw.you_need_to_pay': 'Bạn cần thanh toán: ',
    'Withdraw.content': 'Nội dung\n(Không bắt buộc)',
    'Withdraw.minimum_transaction_amount_is': 'Số tiền giao dịch tối thiểu là {{min}}',
    'Withdraw.balance_insufficient': 'Số dư của bạn không đủ',
    'Withdraw.withdraw_succeeded': 'Rút tiền thành công',
    'Withdraw.confirm_withdraw': 'Bạn có chắc muốn thực hiện giao dịch không?',

    'Withdraw.24h_limit': 'Giới hạn 24h rút tiền',
    'Withdraw.24h_limit_transfer': 'Giới hạn 24h chuyển tiền',
    'Withdraw.unlimited': 'Vô hạn',
    'Withdraw.hide_assets': 'Ẩn các đồng có số dư thấp',
    'Withdraw.network_fee': 'Phí mạng lưới',
    'Withdraw.24h_remaining_limit': 'Hạn mức còn lại trong 24h',

    'Withdraw.modal_chooose_network.title': 'Chọn mạng lưới',
    'Withdraw.modal_chooose_network.warning': 'Đảm bảo mạng khớp với mạng địa chỉ đã nhập để tránh mất mát khi rút tiền.',
    'Withdraw.modal_chooose_network.text': 'Các mạng không khớp sẽ tự động bị xoá. Chọn một mạng bên dưới',
    'Withdraw.modal_chooose_network.noti_block': 'Bị chặn',

    'Withdraw.modal_recent_address.title': 'Danh sách các địa chỉ rút gần nhất',
    'Withdraw.modal_recent_address.warning': 'Đảm bảo mạng khớp với mạng địa chỉ đã nhập để tránh mất mát khi rút tiền.',
    'Withdraw.modal_recent_address.text': 'Các mạng không khớp sẽ tự động bị xoá. Chọn một mạng bên dưới',
    'Withdraw.modal_recent_address.noti_block': 'Bị chặn',
  },
};
